### ISSUE TITLE
unable to use after first  command without sudo.

### ISSUE THREAD

**Issue by joshmanders** [dokku/dokku-daemon#17]
After I run `sudo systemctl restart dokku-daemon.service` I can issue a single command to the socket and get a result, after that nothing and I can't figure out why. If I prefix `nc -U ...` with `sudo` it works, or if I prefix the whole command with `sudo -u dokku ...` to execute as dokku user it works.

![](https://i.imgur.com/RQ9wbE0.png)

**Comment by joshmanders** [comment]
After talking with @josegonzalez I tested on 14.04 and it works, so it seems to be only 16.04

**Comment by josegonzalez** [comment]
Probably systemd related if anything.

**Comment by joshmanders** [comment]
Any idea on how we can fix it? I don't know anything about systemd, but if steered in the right direction, I will submit a PR fixing it.

**Comment by arvinsingla** [comment]
@joshmanders Were you ever able to resolve this issue?
