### ISSUE TITLE
Add the ability to clear the command cache

### ISSUE THREAD

**Issue by josegonzalez** [dokku/dokku-daemon#2]

**Comment by joshmcrae** [comment]
As it currently stands, valid command names are cached in a single file and checked any time a command is issued to the daemon. Clients may send the command "refresh" to the daemon which will result in the cache being _replaced_ with an up-to-date list of the names.

@josegonzalez  From what I can see this enhancement is already a feature so I'll close the issue, but please let me know if I've misunderstood :)

**Comment by josegonzalez** [comment]
Ah, `refresh` is already a command? Guess I didn't read your code carefully enough!
