### ISSUE TITLE
Unable to use some commands

### ISSUE THREAD

**Issue by liamcottle** [dokku/dokku-daemon#23]
It appears that the checking of a valid command prevents some commands from working.

When sending the command `config:set --no-restart app key=value` to the daemon, `Invalid Command` is returned.

I can bypass this by disabling the [valid command checks](https://github.com/dokku/dokku-daemon/blob/master/bin/dokku-daemon#L87) in the daemon script, but I'm sure they're there for security reasons.

**Comment by josegonzalez** [comment]
What version of Dokku are you running?

**Comment by liamcottle** [comment]
`0.12.12`

**Comment by josegonzalez** [comment]
This was a bug in how the help output is generated in golang plugins, please upgrade to the latest version of Dokku.

**Comment by liamcottle** [comment]
Updated to `v0.14.5` and after restarting the `dokku-daemon` service, all is working. Thanks dude!
