### ISSUE TITLE
Problem with socat

### ISSUE THREAD

**Issue by rawnly** [dokku/dokku-daemon#24]
That's the result of my `sudo make install`

```
rm -f /usr/bin/dokku-daemon /etc/init/dokku-daemon.conf /etc/systemd/system/dokku-daemon.service
cp -f bin/dokku-daemon /usr/bin/dokku-daemon
cp -f init/dokku-daemon.service /etc/systemd/system/dokku-daemon.service
systemctl daemon-reload
make socat
make[1]: Entering directory '/root/dokku-daemon'
make[1]: Nothing to be done for 'socat'.
make[1]: Leaving directory '/root/dokku-daemon'
```

**Comment by josegonzalez** [comment]
That message from Make means socat is installed. There isn't any problem with scout otherwise.

**Comment by rawnly** [comment]
Oh ok sorry but i don’t have any  file in my /var/run/dokku-daemon..

— Federico Vitale
Il 17 apr 2019, 23:03 +0200, Jose Diaz-Gonzalez , ha scritto:

**Comment by josegonzalez** [comment]
You installed it, and didn't start the process. You'll need to start the service if you want a socket to exist.
