### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by dean1012** [dokku/dokku-daemon#26]
It looks like tests on the master branch after merging #25 have failed due to what looks to be a fluke issue.

Can you please trigger a Travis run on the master branch manually to verify that tests actually do succeed @josegonzalez 

If tests still fail, i'll need to investigate.

**Comment by josegonzalez** [comment]
Restarted here: https://travis-ci.org/dokku/dokku-daemon/jobs/600531622

**Comment by dean1012** [comment]
So odd...

Travis passed on my final commit and it appears it also passed on the PR.

It seems to consistently fail now though here:

```
Preparing to unpack .../dokku_0.19.2_amd64.deb ...
[....] Reloading nginx configuration (via systemctl): nginx.service7 ok 8Error: keyfile '/root/.ssh/id_rsa.pub' not found.
       you can enter a new keyfile path when you restart the installation.
dpkg: error processing archive /var/cache/apt/archives/dokku_0.19.2_amd64.deb (--unpack):
 new dokku package pre-installation script subprocess returned error exit status 1
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Errors were encountered while processing:
 /var/cache/apt/archives/dokku_0.19.2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
Makefile:66: recipe for target 'setup-travis' failed
make: *** [setup-travis] Error 100
The command "sudo -E make setup-travis" failed and exited with 2 during .
```

Tomorrow i'll pull up an Ubuntu Bionic image and try the tests locally to verify everything. In the meantime, if you have any thoughts (or anyone else) i'm all ears.

**Comment by dean1012** [comment]
So it seems that the last successful TravisCI run (with no code changes after that) was 8 days ago. That would coincide with the release of dokku version 0.19.0.

I am thinking that something happened with either dokku version 0.19.1 or 0.19.2 that is causing the installation error of dokku here.

I will bring up a fresh Ubuntu Bionic tomorrow and try installation of both 0.19.1 and 0.19.2 from a fresh system and try to determine if there is in fact an issue with dokku (and if there is, I will create an issue on that repo) or if it's something else entirely.

On a side note, I also identified a bug in the TravisCI configuration. Specifically, the dokku version environment variable is defined twice so in effect it always will be master.

I will create a pull request that removes the second DOKKU_VERSION variable and keeps the one that sets it to master.

**Comment by josegonzalez** [comment]
Yeah its not clear to me why the keyfile stuff broke since I haven't touched that in a while, so worth checking that out I guess...

**Comment by josegonzalez** [comment]
Tests pass now. Thanks!
