### ISSUE TITLE
Consider making an official release

### ISSUE THREAD

**Issue by ltalirz** [dokku/dokku-daemon#28]
I notice that the dokku-daemon version number was increased to 0.0.2 here https://github.com/dokku/dokku-daemon/commit/a4cdb18d7aea7501f8fa4e82759526aee1117fd3 but the git repository does not have any tagged releases yet.

This makes it difficult to spot outdated dependencies on dokku-daemon and likely contributed to dokku-daemon being overlooked when updating the dependencies of the dokku ansible role.

**Comment by josegonzalez** [comment]
Tagged and released.
